### PR TITLE
adding transition delay variable

### PR DESCRIPTION
**Pull request by CarlVerret**
In this PR, I added transition delay variable, allowing the developper to delay the apparition of the tooltip.  In some cases, it is more instersting to have a small delay.

### CODE REVIEW

**Comment by CarlVerret** [comment]
Hello @CreativeBulma, is this repo still maintained ?
Thanks.

**Comment by karelv** [comment]
I'm interested in this feature, can it be merged? 
Thanks,
K.

**Comment by karelv** [comment]
👍

**Comment by CarlVerret** [comment]
> 👍

it's been a while !  I even forgot I did this PR ! ;)

**Pull request closed without merging**
